--CRIAÇÃO DO USUÁRIO C##LIV_LES
CREATE USER C##LIV_LES IDENTIFIED BY "123FATEC";

--PERMISSÕES
GRANT UNLIMITED TABLESPACE TO C##LIV_LES;
GRANT CONNECT, RESOURCE TO C##LIV_LES;
GRANT CREATE SESSION TO C##LIV_LES;

--CRIAÇÃO DAS TABELAS
CREATE TABLE C##LIV_LES.CLIENTES
(
	"CLI_ID" NUMBER(6,0),
	"CLI_PNOME" VARCHAR2(30),
	"CLI_MNOME" VARCHAR2(30),
	"CLI_UNOME" VARCHAR2(30),
	"CLI_EMAIL" VARCHAR2(50),
	"CLI_GENERO" VARCHAR2(30),
	"CLI_DATANASC" DATE,
	"CLI_CPF" VARCHAR2(11),
	"CLI_RANKING" NUMBER(3) DEFAULT 0,
	"CLI_STATUS" NUMBER(1)
);

CREATE TABLE C##LIV_LES.ENDERECOS
(
	"END_ID" NUMBER(6,0),
	"END_APELIDO" VARCHAR2(30),
	"END_TIPO_RESIDENCIA" NUMBER(2),
	"END_TIPO_LOGRADOURO" NUMBER(2),
	"END_LOGRADOURO" VARCHAR2(50),
	"END_NUMERO" NUMBER(5),
	"END_BAIRRO" VARCHAR2(30),
	"END_CEP" VARCHAR2(8),
	"END_OBS" VARCHAR2(155),
	"END_CIDADE" VARCHAR2(50),
	"END_ESTADO" VARCHAR2(50),
	"END_PAIS" VARCHAR2(50),
	"END_CLI_ID" NUMBER(6,0)
);

CREATE TABLE C##LIV_LES.TELEFONES
(
	"TEL_ID" NUMBER(6,0),
	"TEL_DDI" VARCHAR2(4),
	"TEL_DDD" VARCHAR2(3),
	"TEL_NUMERO" VARCHAR2(9),
	"TEL_TIPO" NUMBER(2),
	"TEL_CLI_ID" NUMBER(6)
);

CREATE TABLE C##LIV_LES.BANDEIRAS
(
	"BAN_ID" NUMBER(6,0),
	"BAN_NOME" VARCHAR2(30)
);

CREATE TABLE C##LIV_LES.CARTOES
(
	"CAR_ID" NUMBER(6,0),
	"CAR_NUMERO" VARCHAR2(16),
	"CAR_NOME" VARCHAR2(90),
	"CAR_COD" VARCHAR2(3),
	"CAR_CLI_ID" NUMBER(6,0),
	"CAR_BAN_ID" NUMBER(6,0)
);

--PRIMARY KEY

ALTER TABLE C##LIV_LES.CLIENTES
	ADD CONSTRAINT PK_CLI PRIMARY KEY (CLI_ID);
		
ALTER TABLE C##LIV_LES.ENDERECOS
	ADD CONSTRAINT PK_END PRIMARY KEY (END_ID);

ALTER TABLE C##LIV_LES.TELEFONES
	ADD CONSTRAINT PK_TEL PRIMARY KEY (TEL_ID);

ALTER TABLE C##LIV_LES.BANDEIRAS
	ADD CONSTRAINT PK_BAN PRIMARY KEY (BAN_ID);
	
ALTER TABLE C##LIV_LES.CARTOES
	ADD CONSTRAINT PK_CAR PRIMARY KEY (CAR_ID);
	
--FOREIGN KEY - ENDERECOS
ALTER TABLE C##LIV_LES.ENDERECOS -- RELACIONAMENTO N-1 (END - CLI)
	ADD CONSTRAINT FK_END_CLI FOREIGN KEY (END_CLI_ID) REFERENCES C##LIV_LES.CLIENTES(CLI_ID);

--FOREIGN KEY - TELEFONES
ALTER TABLE C##LIV_LES.TELEFONES -- RELACIONAMENTO N-1 (TEL - CLI)
	ADD CONSTRAINT FK_TEL_CLI FOREIGN KEY (TEL_CLI_ID) REFERENCES C##LIV_LES.CLIENTES(CLI_ID);

--FOREIGN KEY - CARTOES
ALTER TABLE C##LIV_LES.CARTOES -- RELACIONAMENTO N-1 (CAR - BAN)
	ADD CONSTRAINT FK_CAR_BAN FOREIGN KEY (CAR_BAN_ID) REFERENCES C##LIV_LES.BANDEIRAS(BAN_ID);
	
-- CRIAÇÃO DA SEQUENCE
CREATE SEQUENCE C##LIV_LES.SQ_CLI 
INCREMENT BY 1 
START WITH 1 
NOCACHE
;

CREATE SEQUENCE C##LIV_LES.SQ_END 
INCREMENT BY 1 
START WITH 1 
NOCACHE
;

CREATE SEQUENCE C##LIV_LES.SQ_TEL
INCREMENT BY 1 
START WITH 1 
NOCACHE
;

CREATE SEQUENCE C##LIV_LES.SQ_BAN
INCREMENT BY 1 
START WITH 1 
NOCACHE
;

CREATE SEQUENCE C##LIV_LES.SQ_CAR
INCREMENT BY 1 
START WITH 1 
NOCACHE
;

-- TRIGGERS PARA PEGAR VALOR DA SEQUENCE
CREATE OR REPLACE
TRIGGER C##LIV_LES.TG_SQ_CLI
BEFORE INSERT ON C##LIV_LES.CLIENTES
FOR EACH ROW
WHEN (NEW.CLI_ID IS NULL)
BEGIN
  :NEW.CLI_ID := C##LIV_LES.SQ_CLI.NEXTVAL;
END;
/

CREATE OR REPLACE
TRIGGER C##LIV_LES.TG_SQ_END
BEFORE INSERT ON C##LIV_LES.ENDERECOS
FOR EACH ROW
WHEN (NEW.END_ID IS NULL)
BEGIN
  :NEW.END_ID := C##LIV_LES.SQ_END.NEXTVAL;
END;
/

CREATE OR REPLACE
TRIGGER C##LIV_LES.TG_SQ_TEL
BEFORE INSERT ON C##LIV_LES.TELEFONES
FOR EACH ROW
WHEN (NEW.TEL_ID IS NULL)
BEGIN
  :NEW.TEL_ID := C##LIV_LES.SQ_TEL.NEXTVAL;
END;
/

CREATE OR REPLACE
TRIGGER C##LIV_LES.TG_SQ_BAN
BEFORE INSERT ON C##LIV_LES.BANDEIRAS
FOR EACH ROW
WHEN (NEW.BAN_ID IS NULL)
BEGIN
  :NEW.BAN_ID := C##LIV_LES.SQ_BAN.NEXTVAL;
END;
/

CREATE OR REPLACE
TRIGGER C##LIV_LES.TG_SQ_CAR
BEFORE INSERT ON C##LIV_LES.CARTOES
FOR EACH ROW
WHEN (NEW.CAR_ID IS NULL)
BEGIN
  :NEW.CAR_ID := C##LIV_LES.SQ_CAR.NEXTVAL;
END;
/