INSERT INTO C##LIV_LES.PAPEIS (PAP_ID, PAP_NOME) 
						 VALUES (NULL, 'ROLE_ADMIN');					 

INSERT INTO C##LIV_LES.USUARIOS (USR_ID, USR_NOME_USUARIO, USR_SENHA, USR_CLI_ID, USR_PAP_ID) 
						 VALUES (NULL, 'ADMIN', '$2y$10$NIKjy0mN6MMQOILG1MLzYO9a9pOWyh/s0OFjVCJ01dF1cZfZfz9gK 
', NULL, 1);