--CRIAÇÃO DAS TABELAS
CREATE TABLE C##LIV_LES.LIVROS
(
	"LIV_ID" NUMBER(6,0),
	"LIV_TITULO" VARCHAR2(50),
	"LIV_ANO" NUMBER(4,0),
	"LIV_EDITORA" VARCHAR2(50),
	"LIV_EDICAO" VARCHAR2(50),
	"LIV_ISBN" VARCHAR2(30),
	"LIV_NUM_PAG" NUMBER(8,0),
	"LIV_SINOPSE" VARCHAR2(255),
	"LIV_PRECO_CAPA" NUMBER(8,2),
	"LIV_PRECO_VENDA" NUMBER(8,2),
	"LIV_PESO" NUMBER(5,2),
	"LIV_PROFUNDIDADE" NUMBER(5,2),
	"LIV_STATUS" NUMBER(1,0),
	"LIV_DIM_ID" NUMBER(6,0),
	"LIV_CAP_ID" NUMBER(6,0),
	"LIV_PRC_ID" NUMBER(6,0),
	"LIV_CBR_ID" NUMBER(6,0)
);

CREATE TABLE C##LIV_LES.AUTORES
(
	"AUT_ID" NUMBER(6,0),
	"AUT_NOME" VARCHAR2(100)
);

CREATE TABLE C##LIV_LES.ESCREVEM
(
	"ESC_AUT_ID" NUMBER(6,0),
	"ESC_LIV_ID" NUMBER(6,0)
);

CREATE TABLE C##LIV_LES.DIMENSOES
(
	"DIM_ID" NUMBER(6,0),
	"DIM_NOME" VARCHAR2(30),
	"DIM_ALTURA" NUMBER(5,2),
	"DIM_LARGURA" NUMBER(5,2)
);

CREATE TABLE C##LIV_LES.CAPAS
(
	"CAP_ID" NUMBER(6,0),
	"CAP_URL" VARCHAR2(50),
	"CAP_DESCRICAO" VARCHAR2(155)
);

CREATE TABLE C##LIV_LES.CODIGOS_BARRA
(
	"CBR_ID" NUMBER(6,0),
	"CBR_CODIGO" VARCHAR2(50),
	"CBR_URL" VARCHAR2(50)
);

CREATE TABLE C##LIV_LES.CATEGORIAS
(
	"CAT_ID" NUMBER(6,0),
	"CAT_NOME" VARCHAR2(30),
	"CAT_DESCRICAO" VARCHAR2(155)
);

CREATE TABLE C##LIV_LES.CONJUNTOS_CATEGORIAS
(
	"CCT_LIV_ID" NUMBER(6,0),
	"CCT_CAT_ID" NUMBER(6,0)
);

CREATE TABLE C##LIV_LES.ESTOQUES
(
	"ETQ_ID" NUMBER(6,0),
	"ETQ_QUANTIDADE" NUMBER(10,0),
	"ETQ_VALOR_CUSTO" NUMBER(8,2),
	"ETQ_DATA_ENTRADA" DATE,
	"ETQ_LIV_ID" NUMBER(6,0)
);

CREATE TABLE C##LIV_LES.PRECIFICACOES
(
	"PRC_ID" NUMBER(6,0),
	"PRC_NOME" VARCHAR2(50),
	"PRC_PORCENTAGEM_LUCRO" NUMBER(5,2),
	"PRC_PORCENTAGEM_DESCONTO" NUMBER(5,2)
);


--PRIMARY KEY

ALTER TABLE C##LIV_LES.LIVROS
	ADD CONSTRAINT PK_LIV PRIMARY KEY (LIV_ID);
		
ALTER TABLE C##LIV_LES.AUTORES
	ADD CONSTRAINT PK_AUT PRIMARY KEY (AUT_ID);

ALTER TABLE C##LIV_LES.ESCREVEM
	ADD CONSTRAINT PK_ESC PRIMARY KEY (ESC_AUT_ID, ESC_LIV_ID);

ALTER TABLE C##LIV_LES.DIMENSOES
	ADD CONSTRAINT PK_DIM PRIMARY KEY (DIM_ID);
	
ALTER TABLE C##LIV_LES.CAPAS
	ADD CONSTRAINT PK_CAP PRIMARY KEY (CAP_ID);
	
ALTER TABLE C##LIV_LES.CODIGOS_BARRA
	ADD CONSTRAINT PK_CBR PRIMARY KEY (CBR_ID);
	
ALTER TABLE C##LIV_LES.CATEGORIAS
	ADD CONSTRAINT PK_CAT PRIMARY KEY (CAT_ID);
	
ALTER TABLE C##LIV_LES.CONJUNTOS_CATEGORIAS
	ADD CONSTRAINT PK_CCT PRIMARY KEY (CCT_CAT_ID, CCT_LIV_ID);
		
ALTER TABLE C##LIV_LES.ESTOQUES
	ADD CONSTRAINT PK_ETQ PRIMARY KEY (ETQ_ID);

ALTER TABLE C##LIV_LES.PRECIFICACOES
	ADD CONSTRAINT PK_PRC PRIMARY KEY (PRC_ID);

--FOREIGN KEY - LIVROS
ALTER TABLE C##LIV_LES.LIVROS -- RELACIONAMENTO N-1 (DIM - LIV)
	ADD CONSTRAINT FK_LIV_DIM FOREIGN KEY (LIV_DIM_ID) REFERENCES C##LIV_LES.DIMENSOES(DIM_ID);
	
ALTER TABLE C##LIV_LES.LIVROS -- RELACIONAMENTO N-1 (CAP - LIV)
	ADD CONSTRAINT FK_LIV_CAP FOREIGN KEY (LIV_CAP_ID) REFERENCES C##LIV_LES.CAPAS(CAP_ID);
	
ALTER TABLE C##LIV_LES.LIVROS -- RELACIONAMENTO N-1 (CBR - LIV)
	ADD CONSTRAINT FK_LIV_CBR FOREIGN KEY (LIV_CBR_ID) REFERENCES C##LIV_LES.CODIGOS_BARRA(CBR_ID);

--FOREIGN KEY - ESCREVEM
ALTER TABLE C##LIV_LES.ESCREVEM -- RELACIONAMENTO N-1 (AUT - ESC)
	ADD CONSTRAINT FK_ESC_AUT FOREIGN KEY (ESC_AUT_ID) REFERENCES C##LIV_LES.AUTORES(AUT_ID);

ALTER TABLE C##LIV_LES.ESCREVEM -- RELACIONAMENTO N-1 (LIV - ESC)
	ADD CONSTRAINT FK_ESC_LIV FOREIGN KEY (ESC_LIV_ID) REFERENCES C##LIV_LES.LIVROS(LIV_ID);

--FOREIGN KEY - CONJUNTOS_CATEGORIAS
ALTER TABLE C##LIV_LES.CONJUNTOS_CATEGORIAS -- RELACIONAMENTO N-1 (LIV - CCT)
	ADD CONSTRAINT FK_CCT_LIV FOREIGN KEY (CCT_LIV_ID) REFERENCES C##LIV_LES.LIVROS(LIV_ID);
	
ALTER TABLE C##LIV_LES.CONJUNTOS_CATEGORIAS -- RELACIONAMENTO N-1 (CAT - CCT)
	ADD CONSTRAINT FK_CCT_CAT FOREIGN KEY (CCT_CAT_ID) REFERENCES C##LIV_LES.CATEGORIAS(CAT_ID);
		
--FOREIGN KEY - ESTOQUES
ALTER TABLE C##LIV_LES.ESTOQUES -- RELACIONAMENTO N-1 (LIV - ETQ)
	ADD CONSTRAINT FK_ETQ_LIV FOREIGN KEY (ETQ_LIV_ID) REFERENCES C##LIV_LES.LIVROS(LIV_ID);

	
-- CRIAÇÃO DA SEQUENCE
CREATE SEQUENCE C##LIV_LES.SQ_LIV 
INCREMENT BY 1 
START WITH 1 
NOCACHE
;

CREATE SEQUENCE C##LIV_LES.SQ_AUT 
INCREMENT BY 1 
START WITH 1 
NOCACHE
;

CREATE SEQUENCE C##LIV_LES.SQ_DIM
INCREMENT BY 1 
START WITH 1 
NOCACHE
;

CREATE SEQUENCE C##LIV_LES.SQ_CAP
INCREMENT BY 1 
START WITH 1 
NOCACHE
;

CREATE SEQUENCE C##LIV_LES.SQ_CBR
INCREMENT BY 1 
START WITH 1 
NOCACHE
;

CREATE SEQUENCE C##LIV_LES.SQ_CAT
INCREMENT BY 1 
START WITH 1 
NOCACHE
;

CREATE SEQUENCE C##LIV_LES.SQ_ETQ
INCREMENT BY 1 
START WITH 1 
NOCACHE
;

CREATE SEQUENCE C##LIV_LES.SQ_PRC
INCREMENT BY 1 
START WITH 1 
NOCACHE
;

-- TRIGGERS PARA PEGAR VALOR DA SEQUENCE
CREATE OR REPLACE
TRIGGER C##LIV_LES.TG_SQ_LIV
BEFORE INSERT ON C##LIV_LES.LIVROS
FOR EACH ROW
WHEN (NEW.LIV_ID IS NULL)
BEGIN
  :NEW.LIV_ID := C##LIV_LES.SQ_LIV.NEXTVAL;
END;
/

CREATE OR REPLACE
TRIGGER C##LIV_LES.TG_SQ_AUT
BEFORE INSERT ON C##LIV_LES.AUTORES
FOR EACH ROW
WHEN (NEW.AUT_ID IS NULL)
BEGIN
  :NEW.AUT_ID := C##LIV_LES.SQ_AUT.NEXTVAL;
END;
/

CREATE OR REPLACE
TRIGGER C##LIV_LES.TG_SQ_DIM
BEFORE INSERT ON C##LIV_LES.DIMENSOES
FOR EACH ROW
WHEN (NEW.DIM_ID IS NULL)
BEGIN
  :NEW.DIM_ID := C##LIV_LES.SQ_DIM.NEXTVAL;
END;
/

CREATE OR REPLACE
TRIGGER C##LIV_LES.TG_SQ_CAP
BEFORE INSERT ON C##LIV_LES.CAPAS
FOR EACH ROW
WHEN (NEW.CAP_ID IS NULL)
BEGIN
  :NEW.CAP_ID := C##LIV_LES.SQ_CAP.NEXTVAL;
END;
/

CREATE OR REPLACE
TRIGGER C##LIV_LES.TG_SQ_CBR
BEFORE INSERT ON C##LIV_LES.CODIGOS_BARRA
FOR EACH ROW
WHEN (NEW.CBR_ID IS NULL)
BEGIN
  :NEW.CBR_ID := C##LIV_LES.SQ_CBR.NEXTVAL;
END;
/

CREATE OR REPLACE
TRIGGER C##LIV_LES.TG_SQ_CAT
BEFORE INSERT ON C##LIV_LES.CATEGORIAS
FOR EACH ROW
WHEN (NEW.CAT_ID IS NULL)
BEGIN
  :NEW.CAT_ID := C##LIV_LES.SQ_CAT.NEXTVAL;
END;
/

CREATE OR REPLACE
TRIGGER C##LIV_LES.TG_SQ_ETQ
BEFORE INSERT ON C##LIV_LES.ESTOQUES
FOR EACH ROW
WHEN (NEW.ETQ_ID IS NULL)
BEGIN
  :NEW.ETQ_ID := C##LIV_LES.SQ_ETQ.NEXTVAL;
END;
/

CREATE OR REPLACE
TRIGGER C##LIV_LES.TG_SQ_PRC
BEFORE INSERT ON C##LIV_LES.PRECIFICACOES
FOR EACH ROW
WHEN (NEW.PRC_ID IS NULL)
BEGIN
  :NEW.PRC_ID := C##LIV_LES.SQ_PRC.NEXTVAL;
END;
/