--CRIAÇÃO DAS TABELAS
CREATE TABLE C##LIV_LES.USUARIOS
(
	"USR_ID" NUMBER(6,0),
	"USR_NOME_USUARIO" VARCHAR2(100),
	"USR_SENHA" VARCHAR(255),
	"USR_CLI_ID" NUMBER(6,0),
	"USR_PAP_ID" NUMBER(6,0)
);


CREATE TABLE C##LIV_LES.PERMISSOES
(
	"PER_ID" NUMBER(6,0),
	"PER_NOME" VARCHAR2(100)
);

CREATE TABLE C##LIV_LES.PAPEIS
(
	"PAP_ID" NUMBER(6,0),
	"PAP_NOME" VARCHAR2(100)
);

CREATE TABLE C##LIV_LES.PERMISSOES_PAPEIS
(
	"PPA_PER_ID" NUMBER(6,0),
	"PPA_PAP_ID" NUMBER(6,0)
);

--PRIMARY KEY

ALTER TABLE C##LIV_LES.USUARIOS
	ADD CONSTRAINT PK_USR PRIMARY KEY (USR_ID);
		
ALTER TABLE C##LIV_LES.PERMISSOES
	ADD CONSTRAINT PK_PER PRIMARY KEY (PER_ID);
	
ALTER TABLE C##LIV_LES.PAPEIS
	ADD CONSTRAINT PK_PAP PRIMARY KEY (PAP_ID);	
			
-- CRIAÇÃO DA SEQUENCE
CREATE SEQUENCE C##LIV_LES.SQ_USR 
INCREMENT BY 1 
START WITH 1 
NOCACHE
;

CREATE SEQUENCE C##LIV_LES.SQ_PER 
INCREMENT BY 1 
START WITH 1 
NOCACHE
;

CREATE SEQUENCE C##LIV_LES.SQ_PAP
INCREMENT BY 1 
START WITH 1 
NOCACHE
;

-- TRIGGERS PARA PEGAR VALOR DA SEQUENCE
CREATE OR REPLACE
TRIGGER C##LIV_LES.TG_SQ_USR
BEFORE INSERT ON C##LIV_LES.USUARIOS
FOR EACH ROW
WHEN (NEW.USR_ID IS NULL)
BEGIN
  :NEW.USR_ID := C##LIV_LES.SQ_USR.NEXTVAL;
END;
/

CREATE OR REPLACE
TRIGGER C##LIV_LES.TG_SQ_PER
BEFORE INSERT ON C##LIV_LES.PERMISSOES
FOR EACH ROW
WHEN (NEW.PER_ID IS NULL)
BEGIN
  :NEW.PER_ID := C##LIV_LES.SQ_PER.NEXTVAL;
END;
/

CREATE OR REPLACE
TRIGGER C##LIV_LES.TG_SQ_PAP
BEFORE INSERT ON C##LIV_LES.PAPEIS
FOR EACH ROW
WHEN (NEW.PAP_ID IS NULL)
BEGIN
  :NEW.PAP_ID := C##LIV_LES.SQ_PAP.NEXTVAL;
END;
/